# Instructions ----
#' This file follows the format generated by ecosystemdata:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemdata:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# Setup ----
# Load or prepare any necessary data for testing

# sample_lognormal ----
## IO correctness ----
test_that("sample_lognormal() works with correct inputs", {
  #' @description Test that sample_lognormal(1, 1) returns known result when
  #' the seed is set to a defined value of 123.
  set.seed(123)
  expect_equal(
    object = sample_lognormal(1, 1),
    expected = 0.346291059
  )

  #' @description Test that sample_lognormal(1) returns two different values
  #' when the seed is not set.
  expect_false(
    sample_lognormal(1) == sample_lognormal(1)
  )

  x <- 1:5
  #' @description Test that sample_lognormal() returns the input values when
  #' the standard deviation is set to zero.
  expect_equal(
    sample_lognormal(x, sd = 0),
    x
  )

  set.seed(1)
  #' @description Test that sample_lognormal() returns the correct values when
  #' the standard deviation is zero and a positive value. This test was created
  #' to ensure that the inputs are duplicated in the correct way as part of a
  #' bug found in [PR #2](https://github.com/NOAA-FIMS/ecosystemom/pull/2).
  expect_equal(
    sample_lognormal(1, sd = c(0, 1)),
    c(1.0000000, 0.324180827)
  )
})

## Edge handling ----
test_that("sample_lognormal() returns correct outputs for edge cases", {
  #' @description Test that sample_lognormal() returns a vector when a vector
  #' is passed to `x` but a single value is passed to `sd`.
  expect_equal(
    object = length(sample_lognormal(1:5, 1)),
    expected = 5
  )

  #' @description Test that sample_lognormal() returns a vector when a single
  #' value is passed to `x` but a vector is passed to `sd`.
  expect_equal(
    object = length(sample_lognormal(1, 1:5)),
    expected = 5
  )

  #' @description Test that sample_lognormal() returns a valid answer when an
  #' integer is passed to `x`.
  expect_no_error(
    object = sample_lognormal(1L, 1)
  )

  #' @description Test that sample_lognormal() returns a valid answer when a
  #' double is passed to `x`.
  expect_no_error(
    object = sample_lognormal(1.0, 1)
  )
})

## Error handling ----
test_that("sample_lognormal() returns correct error messages", {
  #' @description Test that sample_lognormal() returns expected error when two
  #' different size vectors are passed.
  expect_error(
    object = sample_lognormal(1:5, 1:10),
    regexp = "Length of `x` and `sd` must be the same"
  )
  #' @description Test that sample_lognormal() returns expected error when
  #' a negative value is passed to `sd`.
  expect_error(
    object = sample_lognormal(1, -1),
    regexp = "All values of `sd` must be positive"
  )
})
