# Instructions ----
#' This file follows the format generated by ecosystemom:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemom:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# estimate_true_maturity ----
## Setup ----
# Create synthetic maturity values (proportions between 0 and 1)
test_ages_vector <- c(1, 2, 3, 4, 5, 6, 7)
test_proportions_vector <- c(0, 0.1, 0.5, 0.9, 1.0, 1.0, 1.0)

expected_fims_maturity_cols <- c(
  "model_family", "module_name", "fleet_name", "module_type", "label",
  "age", "length", "time", "value",
  "estimation_type", "distribution_type", "distribution"
)

## IO correctness ----
test_that("estimate_true_maturity() logistic form works with correct inputs", {
  res <- estimate_true_maturity(
    ages = test_ages_vector,
    spawning_proportion = test_proportions_vector,
    functional_form = "logistic"
  )

  #' @description Test that estimate_true_maturity() returns the standard NOAA-FIMS structured columns.
  expect_equal(
    object = colnames(res),
    expected = expected_fims_maturity_cols
  )

  #' @description Test that maturity output routes to catch_at_age for FIMS model family.
  expect_equal(
    object = unique(res[["model_family"]]),
    expected = "catch_at_age"
  )

  #' @description Test that maturity output explicitly flags the module_name as Maturity.
  expect_equal(
    object = unique(res[["module_name"]]),
    expected = "Maturity"
  )

  #' @description Test that maturity logistic form outputs only 'inflection_point' and 'slope' labels.
  expect_equal(
    object = res[["label"]],
    expected = c("inflection_point", "slope")
  )

  #' @description Test that the estimation_type defaults to constant for fixed assessment parameter entry blocks.
  expect_equal(
    object = unique(res[["estimation_type"]]),
    expected = "constant"
  )

  #' @description Test that the calculated parameter estimates return as real numeric doubles.
  expect_type(
    object = res[["value"]],
    type = "double"
  )
})

test_that("estimate_true_maturity() fits parameters accurately from expected base profiles", {
  # Generate a mathematically perfect logistic maturity ogive with inflection = 4.0 and slope = 1.5
  perfect_ages <- 1:7
  perfect_proportions <- 1.0 / (1.0 + exp(-1.5 * (perfect_ages - 4.0)))

  res <- estimate_true_maturity(
    ages = perfect_ages,
    spawning_proportion = perfect_proportions,
    functional_form = "logistic"
  )

  inflection_val <- res |> 
    dplyr::filter(label == "inflection_point") |> 
    dplyr::pull(value)

  slope_val <- res |> 
    dplyr::filter(label == "slope") |> 
    dplyr::pull(value)

  #' @description Test that the Sum of Squares optimizer extracts the exact inflection point from stable source data.
  expect_equal(object = inflection_val, expected = 4.0, tolerance = 0.1)

  #' @description Test that the Sum of Squares optimizer extracts the exact maturity slope from stable source data.
  expect_equal(object = slope_val, expected = 1.5, tolerance = 0.1)
})

## Edge handling ----
test_that("estimate_true_maturity() resolves knife-edge or sharp transition step vectors without collapsing", {
  # Extreme sharp transition step (0 to 1 instantly) common in basic Ecopath models
  knife_edge_proportions <- c(0, 0, 0, 1, 1, 1, 1)

  #' @description Test that a sudden knife-edge step function calculates finite parameter approximations without optimization crashes.
  expect_silent({
    res <- estimate_true_maturity(
      ages = test_ages_vector,
      spawning_proportion = knife_edge_proportions,
      functional_form = "logistic"
    )
  })
  
  expect_true(all(is.finite(res[["value"]])))
})

test_that("estimate_true_maturity() safely processes complete absolute boundary arrays", {
  all_zeros <- rep(0.0, length(test_ages_vector))
  all_ones  <- rep(1.0, length(test_ages_vector))

  #' @description Test that a vector comprised completely of absolute zeros returns stable numeric solutions.
  expect_true(
    all(is.finite(estimate_true_maturity(test_ages_vector, all_zeros)[["value"]]))
  )

  #' @description Test that a vector comprised completely of absolute ones returns stable numeric solutions.
  expect_true(
    all(is.finite(estimate_true_maturity(test_ages_vector, all_ones)[["value"]]))
  )
})

## Error handling ----
test_that("estimate_true_maturity() catches input mismatches and illegal boundaries", {
  #' @description Test that validation fails with an error if the ages and proportions arrays have unequal lengths.
  expect_error(
    object = estimate_true_maturity(ages = c(1, 2, 3), spawning_proportion = c(0, 0.5)),
    regexp = "must be of equal length"
  )

  #' @description Test that input validations throw an error if elements drop below the 0 probability limit.
  expect_error(
    object = estimate_true_maturity(ages = c(1, 2), spawning_proportion = c(-0.1, 0.5)),
    regexp = "must be between 0 and 1"
  )

  #' @description Test that input validations throw an error if elements exceed the 1 probability limit.
  expect_error(
    object = estimate_true_maturity(ages = c(1, 2), spawning_proportion = c(0.5, 1.2)),
    regexp = "must be between 0 and 1"
  )

  #' @description Test that structural matching crashes if an illegal functional_form string option is requested.
  expect_error(
    object = estimate_true_maturity(test_ages_vector, test_proportions_vector, functional_form = "invalid_form")
  )
})