# Instructions ----
#' This file follows the format generated by ecosystemom:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemom:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# get_functional_groups ----
## IO correctness ----
test_that("get_functional_groups() works with correct inputs", {
  #' @description Test that get_functional_groups() returns a tibble from a valid CSV.
  fg_csv_path <- tempfile(fileext = ".csv")
  file_content <- c(
    ',"Group name","Trophic level","Hab area (proportion)","Biomass in habitat area (1e6 mt)","Biomass (1e6 mt)","Total mortality (/year)","Production / biomass (/year)","Consumption / biomass (/year)","Ecotrophic Efficiency","Production / consumption (/year)","Biomass accumulation (1e6 mt)","BA rate (/year)",',
    ",bluefish,,,,,,,,,,,,",
    '12,"bluefish juv",3.958791,1,0.00432475,0.00432475,2.069,,12.33118,0.8549753,0.167786,-0.0002763515,-0.0639,',
    '13,"bluefish adult",3.902977,1,0.2197,0.2197,0.656,,3.139,0.2286296,0.2089838,-0.01403883,-0.0639,',
    '11,"spiny dogfish",3.384795,1,0.2715,0.2715,,0.321,1.81,0.06278656,0.1773481,,,',
    "22,Detritus,1,1,12.974,12.974,,,,0.374267,,,,",
    "18,anchovies,3.02654,1,0.2713,0.2713,,2.2,7.333,0.4326596,0.3000136,,,"
  )
  writeLines(paste(file_content, collapse = "\n"), fg_csv_path)
  on.exit(unlink(fg_csv_path))

  expect_equal(
    object = get_functional_groups(fg_csv_path),
    expected = split_functional_groups(
      c("bluefish juv", "bluefish adult", "spiny dogfish", "Detritus", "anchovies")
    )
  )
})

test_that("get_functional_groups() works with real data", {
  #' @description Test that get_functional_groups() can read a real data file.
  real_data_path <- system.file(
    "extdata", "ewe_ecosim_base_nwatlantic", "basic_estimates.csv",
    package = "ecosystemom"
  )
  # system.file returns "" if file not found in installed package.
  # This happens during dev, so we build path from project root.
  if (real_data_path == "") {
    real_data_path <- file.path("inst", "extdata", "ewe_ecosim_base_nwatlantic", "basic_estimates.csv")
  }

  # Skip if the file doesn't exist (e.g. in some CI environments)
  testthat::skip_if_not(file.exists(real_data_path), "Test data file not found")

  functional_groups <- get_functional_groups(real_data_path)

  #' @description Test that get_functional_groups() returns a tibble with real data.
  expect_true(tibble::is_tibble(functional_groups))

  #' @description Test that get_functional_groups() returns the correct number of rows.
  # There are 22 functional groups in this file.
  expect_equal(nrow(functional_groups), 22)

  #' @description Test that get_functional_groups() returns the correct number of columns.
  expect_equal(ncol(functional_groups), 4)

  #' @description Test that get_functional_groups() returns the correct species.
  expect_equal(
    object = functional_groups |>
      dplyr::pull(species) |>
      unique(),
    expected = c(
      "striped bass", "menhaden", "spiny dogfish", "bluefish", "weakfish",
      "Atlantic herring", "anchovies", "benthos", "zooplankton", "phytoplankton",
      "Detritus"
    )
  )

  #' @description Test that get_functional_groups() returns the correct groups.
  expect_equal(
    object = functional_groups |>
      dplyr::pull(group) |>
      unique(),
    expected = c(
      "0", "2-5", "6+", "1", "2", "3", "4", "5", NA_character_, "juv", "adult", "0-1", "2+"
    )
  )

  #' @description Test a specific parsing from the real data for 'bluefish'.
  bluefish_juv <- functional_groups[functional_groups$functional_group == "bluefish juv", ]
  expect_equal(bluefish_juv$species, "bluefish")
  expect_equal(bluefish_juv$group, "juv")
  bluefish_adult <- functional_groups[functional_groups$functional_group == "bluefish adult", ]
  expect_equal(bluefish_adult$species, "bluefish")
  expect_equal(bluefish_adult$group, "adult")
})

## Edge handling ----
test_that("get_functional_groups() returns correct outputs for edge cases", {
  #' @description Test get_functional_groups() with an empty file.
  empty_csv_path <- tempfile(fileext = ".csv")
  file.create(empty_csv_path)
  on.exit(unlink(empty_csv_path))
  expect_error(
    object = get_functional_groups(empty_csv_path),
    regexp = "no lines available in input"
  )

  #' @description Test get_functional_groups() with a header-only file.
  header_only_csv_path <- tempfile(fileext = ".csv")
  writeLines("Code,Name,Type", header_only_csv_path)
  on.exit(unlink(header_only_csv_path), add = TRUE)
  expect_error(
    object = get_functional_groups(header_only_csv_path),
    regexp = "no lines available in input"
  )
})

## Error handling ----
test_that("get_functional_groups() returns correct error messages", {
  #' @description Test get_functional_groups() with a non-existent file.
  expect_error(
    expect_warning(
      get_functional_groups("non_existent_file.csv"),
      regexp = "cannot open file" # Catches the warning
    ),
    regexp = "cannot open the connection" # Catches the error
  )
})
