# Instructions ----
#' This file follows the format generated by ecosystemom:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemom:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# Setup ----

# Expected column names in the output
expected_cols <- c(
  "year", "prey", "predator", "proportion",
  "prey_snake_case", "predator_snake_case"
)

# IO correctness ----
test_that("load_diet_composition() works with correct inputs", {
  withr::with_tempdir({
    # Create a sample CSV for the 'ewe_ecospace_yearly' format
    ecospace_yearly_data <- data.frame(
      Year = c(2000, 2001),
      "Predator A | Prey 1" = c(10, 20),
      "Predator A | Prey 2" = c(30, 40),
      check.names = FALSE
    )
    ecospace_yearly_path <- "ecospace_yearly.csv"
    write.csv(ecospace_yearly_data, ecospace_yearly_path, row.names = FALSE)

    #' @description Test that load_diet_composition() correctly processes ewe_ecospace_yearly format.
    result_yearly <- load_diet_composition("ecospace_yearly.csv", verbose = FALSE)
    expect_true(tibble::is_tibble(result_yearly))
    expect_equal(colnames(result_yearly), expected_cols)
    expect_equal(nrow(result_yearly), 4)
    expect_equal(result_yearly[["proportion"]][1], 10 / (10 + 30))
    expect_equal(result_yearly[["proportion"]][2], 30 / (10 + 30))
    expect_equal(result_yearly[["prey_snake_case"]][1], "prey_1")
    expect_equal(result_yearly[["predator_snake_case"]][1], "predator_a")

    # Create a sample CSV for the 'ewe_ecopath' format
    ecopath_data <- data.frame(
      "Prey \\ predator" = c("Prey 1", "Prey 2"),
      "Predator A" = c(0.25, 0.75),
      "Predator B" = c(0.6, 0.4),
      check.names = FALSE
    )
    ecopath_path <- "ecopath.csv"
    write.csv(ecopath_data, ecopath_path, row.names = FALSE)

    #' @description Test that load_diet_composition() correctly processes ewe_ecopath format.
    result_ecopath <- load_diet_composition("ecopath.csv", verbose = FALSE)
    expect_true(tibble::is_tibble(result_ecopath))
    expect_equal(colnames(result_ecopath), expected_cols)
    expect_equal(nrow(result_ecopath), 4)
    expect_true(all(is.na(result_ecopath[["year"]])))
    expect_equal(
      result_ecopath |>
        dplyr::filter(predator == "Predator A", prey == "Prey 1") |>
        dplyr::pull(proportion),
      0.25
    )
    expect_equal(result_ecopath[["prey_snake_case"]][1], "prey_1")
    expect_equal(result_ecopath[["predator_snake_case"]][2], "predator_b")
  })
})

test_that("load_diet_composition() works with real data", {
  withr::with_tempdir({
    ewe_ecosim_with_environmental_data_nwatlantic_path <- system.file(
      "extdata", "ewe_ecosim_with_environmental_data_nwatlantic",
      package = "ecosystemom"
    )
    if (ewe_ecosim_with_environmental_data_nwatlantic_path == "") {
      ewe_ecosim_with_environmental_data_nwatlantic_path <- file.path(
        "inst", "extdata", "ewe_ecosim_with_environmental_data_nwatlantic"
      )
    }
    diet_composition <- load_diet_composition(
      fs::path(
        ewe_ecosim_with_environmental_data_nwatlantic_path, "diet_composition.csv"
      ),
      verbose = FALSE
    )
    functional_groups <- get_functional_groups(
      fs::path(ewe_ecosim_with_environmental_data_nwatlantic_path, "basic_estimates.csv")
    )
    expect_equal(
      object = diet_composition |>
        dplyr::pull(prey) |>
        unique(),
      expected = functional_groups[["functional_group"]]
    )

    expect_equal(
      object = colnames(diet_composition),
      expected = c(
        "year", "prey", "predator", "proportion", "prey_snake_case", "predator_snake_case"
      )
    )

    expect_equal(
      object = diet_composition |>
        dplyr::pull(year) |>
        unique(),
      expected = NA
    )
  })
})

# Edge handling ----
test_that("load_diet_composition() handles edge cases", {
  withr::with_tempdir({
    # Test with an empty file
    empty_path <- "empty.csv"
    file.create(empty_path)
    #' @description Test that load_diet_composition() errors on empty file.
    expect_error(
      load_diet_composition(empty_path, verbose = FALSE),
      "no lines available in input"
    )

    # Test with a file containing only headers
    header_only_data <- data.frame(
      "Prey \\ predator" = character(),
      "Predator A" = character(),
      check.names = FALSE
    )
    header_only_path <- "header_only.csv"
    write.csv(header_only_data, header_only_path, row.names = FALSE)

    #' @description Test that load_diet_composition() handles header-only file.
    result_header <- load_diet_composition("header_only.csv", verbose = FALSE)
    expect_true(tibble::is_tibble(result_header))
    expect_equal(nrow(result_header), 0)
    expect_equal(colnames(result_header), expected_cols)

    # Test ecopath format with empty column names from EwE output
    ecopath_empty_col_data <- data.frame(
      "Prey \\ predator" = c("Prey 1", "Prey 2"),
      "Predator A" = c(0.25, 0.75),
      "temp" = c(NA, NA),
      check.names = FALSE
    )
    colnames(ecopath_empty_col_data)[3] <- ""
    ecopath_empty_col_path <- "ecopath_empty_col.csv"
    write.csv(ecopath_empty_col_data, ecopath_empty_col_path, row.names = FALSE)

    #' @description Test that load_diet_composition() handles EwE ecopath format with empty columns.
    result_empty_col <- load_diet_composition("ecopath_empty_col.csv", verbose = FALSE)
    expect_true(tibble::is_tibble(result_empty_col))

    pred_a_data <- result_empty_col |>
      dplyr::filter(predator == "Predator A")
    expect_equal(nrow(pred_a_data), 2)
    expect_equal(pred_a_data[["prey"]], c("Prey 1", "Prey 2"))
    expect_equal(pred_a_data[["proportion"]], c(0.25, 0.75))
  })
})

# Error handling ----
test_that("load_diet_composition() returns correct error messages", {
  withr::with_tempdir({
    # Test with an unsupported format
    unknown_format_data <- data.frame(
      Col1 = c(1, 2),
      Col2 = c(3, 4)
    )
    unknown_format_path <- "unknown.csv"
    write.csv(unknown_format_data, unknown_format_path, row.names = FALSE)

    #' @description Test that load_diet_composition() errors on unknown file format.
    expect_error(
      load_diet_composition(unknown_format_path),
      "Unknown diet file format."
    )

    # Test with 'ewe_ecospace_monthly' which is detected but not implemented
    monthly_format_data <- data.frame(
      TimeStep = c(1, 2),
      "Predator A | Prey 1" = c(10, 20),
      check.names = FALSE
    )
    monthly_format_path <- "monthly.csv"
    write.csv(monthly_format_data, monthly_format_path, row.names = FALSE)

    #' @description Test that load_diet_composition() errors on unimplemented monthly format.
    expect_error(
      load_diet_composition(monthly_format_path, verbose = FALSE),
      "The 'ewe_ecospace_monthly' format is recognized but not yet supported."
    )

    # Test with duplicate predator names in 'ewe_ecopath' format
    duplicate_predator_data <- data.frame(
      "Prey \\ predator" = c("Prey 1", "Prey 1", "Prey 2"),
      "Predator A" = c(0.25, 0.75, 0.5),
      check.names = FALSE
    )
    duplicate_predator_path <- "duplicate_predator.csv"
    write.csv(duplicate_predator_data, duplicate_predator_path, row.names = FALSE)

    #' @description Test that load_diet_composition() errors on duplicate predator names.
    expect_error(
      load_diet_composition(duplicate_predator_path, verbose = FALSE),
      "Duplicate predator names found"
    )
  })

  #' @description Test that load_diet_composition() errors when file does not exist.
  expect_error(
    load_diet_composition("non_existent_file.csv", verbose = FALSE)
  )
})
