# Instructions ----
#' This file follows the format generated by ecosystemom:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemom:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# estimate_true_selectivity ----
## Setup ----
# Create a robust synthetic dataset mimicking a single species with annual age-structured fishing mortality
set.seed(42)
years <- 2020:2022
groups <- c("age1", "age2", "age3", "age4")
true_ages <- c("age1" = 1, "age2" = 2, "age3" = 3, "age4" = 4)

# Logistic curve generation tool for realistic synthetic data
mock_logistic <- function(x) { 
  1 / (1 + exp(-1.5 * (x - 2.5))) 
}

synthetic_data <- expand.grid(
  species_name = "Cod",
  truth_group = groups,
  truth_label = "fishing_mortality",
  truth_type = "agecomp",
  truth_time_step = "yearly", 
  truth_unit = "year^-1",
  truth_year = years,
  stringsAsFactors = FALSE
) |>
  dplyr::mutate(
    # Map groups to realistic values with random gamma noise
    age_num = true_ages[truth_group],
    base_val = mock_logistic(age_num),
    truth_value = stats::rgamma(dplyr::n(), shape = 20, scale = base_val / 20)
  ) |>
  dplyr::select(-age_num, -base_val) |>
  tibble::as_tibble()

expected_fims_cols <- c(
  "model_family", "module_name", "fleet_name", "module_type", "label",
  "age", "length", "time", "value",
  "estimation_type", "distribution_type", "distribution"
)

## IO correctness ----
test_that("estimate_true_selectivity() logistic form works with correct inputs", {
  res <- estimate_true_selectivity(
    data = synthetic_data,
    ages = true_ages,
    functional_form = "logistic"
  )

  #' @description Test that estimate_true_selectivity() returns the standard NOAA-FIMS structured columns.
  expect_equal(
    object = colnames(res),
    expected = expected_fims_cols
  )

  #' @description Test that logistic form outputs only 'inflection_point' and 'slope' labels.
  expect_equal(
    object = unique(res[["label"]]),
    expected = c("inflection_point", "slope")
  )

  #' @description Test that the output contains rows for all years present in the source dataset if parameters vary.
  expect_equal(
    object = sort(unique(res[["time"]])),
    expected = sort(years)
  )

  #' @description Test that the return values for estimated parameters are real numeric vectors.
  expect_type(
    object = res[["value"]],
    type = "double"
  )
})

test_that("estimate_true_selectivity() double_logistic form works with correct inputs", {
  res <- estimate_true_selectivity(
    data = synthetic_data,
    ages = true_ages,
    functional_form = "double_logistic"
  )

  #' @description Test that double_logistic form outputs four parameters for ascending and descending limbs.
  expect_equal(
    object = unique(res[["label"]]),
    expected = c("inflection_point_asc", "slope_asc", "inflection_point_desc", "slope_desc")
  )
})

test_that("estimate_true_selectivity() works with data from the package", {
  # Load package data
  data(ewe_ecosim_base_nwatlantic, package = "ecosystemom")

  # Generate truth data for a species
  truth <- calc_truth(ewe_ecosim_base_nwatlantic, species_name = "menhaden")

  # Prepare data for selectivity estimation
  temp_data <- truth |>
    dplyr::filter(
      truth_label == "fishing_mortality",
      truth_type == "agecomp",
      truth_time_step == "yearly"
    ) |>
    tidyr::unnest(cols = truth_om)

  # Define age mapping
  temp_ages <- c("0" = 0, "1" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5, "6+" = 6)

  # Estimate selectivity
  res <- estimate_true_selectivity(
    data = temp_data,
    ages = temp_ages,
    functional_form = "double_logistic"
  )

  #' @description Test that selectivity estimation on package data returns the correct columns.
  expect_equal(object = colnames(res), expected = expected_fims_cols)

  #' @description Test that logistic estimation on package data returns correct parameter labels.
  expect_equal(
    object = sort(unique(res[["label"]])), 
    expected = c("inflection_point_asc", "inflection_point_desc", "slope_asc", "slope_desc")
  )
})

test_that("estimate_true_selectivity() collapses output to time-invariant parameters when values are identical across years", {
  # Modify synthetic data so that every year contains identical truth_values per age group
  invariant_data <- synthetic_data |>
    dplyr::group_by(truth_group) |>
    dplyr::mutate(truth_value = 0.5 * true_ages[truth_group]) |>
    dplyr::ungroup()

  res_collapsed <- estimate_true_selectivity(
    data = invariant_data,
    ages = true_ages,
    functional_form = "logistic"
  )

  #' @description Test that the collapse feature minimizes the result set to exactly 2 rows for logistic form.
  expect_equal(
    object = nrow(res_collapsed),
    expected = 2
  )

  #' @description Test that the collapse feature forces the time column to return NA_integer_.
  expect_true(
    all(is.na(res_collapsed[["time"]]))
  )
  
  res_collapsed_double <- estimate_true_selectivity(
    data = invariant_data,
    ages = true_ages,
    functional_form = "double_logistic"
  )

  #' @description Test that the collapse feature minimizes the result set to exactly 4 rows for double logistic form.
  expect_equal(
    object = nrow(res_collapsed_double),
    expected = 4
  )
})

test_that("estimate_true_selectivity() produces valid parameter estimates on stable target patterns", {
  stable_ages <- c("0" = 0, "1" = 1, "2" = 2, "3" = 3, "4" = 4)
  stable_data <- tibble::tibble(
    species_name = "Cod",
    truth_label = "fishing_mortality",
    truth_type = "agecomp",
    truth_time_step = "yearly",
    truth_unit = "year^-1",
    truth_year = 2020,
    truth_group = names(stable_ages),
    truth_value = 2.0 / (1 + exp(-1.5 * (unname(stable_ages) - 2)))
  )

  res <- estimate_true_selectivity(data = stable_data, ages = stable_ages, functional_form = "logistic")

  inflection <- res |> 
    dplyr::filter(label == "inflection_point") |> 
    dplyr::pull(value)

  slope <- res |> 
    dplyr::filter(label == "slope") |> 
    dplyr::pull(value)

  #' @description Test that inflection_point estimation equals to the expected value.
  expect_equal(object = inflection, expected = 2, tolerance = 0.01)

  #' @description Test that slope estimation equals to the expected value.
  expect_equal(object = slope, expected = 1.5, tolerance = 0.01)
})

test_that("estimate_logistic_parameters() extracts expected curve configurations", {
  test_ages <- 1:10
  logistic_values <- 2.5 / (1 + exp(-1 * (test_ages - 5)))
  
  res <- estimate_logistic_parameters(raw_values = logistic_values, ages = test_ages)
  
  #' @description Test that internal estimate_logistic labels match specific structural outputs.
  expect_equal(object = res[["label"]], expected = c("inflection_point", "slope"))
  
  #' @description Test that internal estimate_logistic values equal to expected values.
  expect_equal(object = res[["value"]], expected = c(5, 1), tolerance = 0.01)
})

test_that("estimate_double_logistic_parameters() extracts expected curve configurations", {
  test_ages <- 1:15
  asc_limb <- 1 / (1 + exp(-1.2 * (test_ages - 4)))
  desc_limb <- 1 / (1 + exp(-0.8 * (test_ages - 11)))
  double_logistic_values <- 3.0 * (asc_limb * (1 - desc_limb))
  
  res <- estimate_double_logistic_parameters(raw_values = double_logistic_values, ages = test_ages)
  
  #' @description Test that internal estimate_double_logistic_labels resolves all 4 expected labels.
  expect_equal(
    object = res[["label"]], 
    expected = c("inflection_point_asc", "slope_asc", "inflection_point_desc", "slope_desc")
  )
  
  #' @description Test that internal estimate_double_logistic values equal to expected values.
  expect_equal(object = res[["value"]], expected = c(4, 1.2, 11, 0.8), tolerance = 0.01)
})

## Edge handling ----
test_that("estimate_true_selectivity() manages edge cases and vector parsing gracefully", {
  numeric_label_data <- synthetic_data |>
    dplyr::mutate(truth_group = as.character(rep(1:4, length(years))))

  #' @description Test that explicit age maps can be left NULL when truth_groups are purely numeric strings.
  expect_silent(
    estimate_true_selectivity(data = numeric_label_data, ages = NULL, functional_form = "logistic")
  )

  shuffled_data <- synthetic_data |>
    dplyr::arrange(dplyr::desc(truth_group))

  #' @description Test that data alignment matches sequential scale sorts even if dataframe rows arrive randomized.
  expect_no_error(
    estimate_true_selectivity(data = shuffled_data, ages = true_ages, functional_form = "logistic")
  )
})

test_that("estimate_true_selectivity() handles flat, zero, and single time frame variations", {
  single_time_data <- synthetic_data |> 
    dplyr::filter(truth_year == 2020)

  res_single <- estimate_true_selectivity(data = single_time_data, ages = true_ages, functional_form = "logistic")
  #' @description Test that evaluation works correctly when passing a single time frame slice.
  expect_equal(object = nrow(res_single), expected = 2)

  flat_data <- single_time_data |> 
    dplyr::mutate(truth_value = 0.5)
  res_flat <- estimate_true_selectivity(data = flat_data, ages = true_ages, functional_form = "logistic")
  #' @description Test that flat selectivity data tracks out finite numeric solutions without crashing.
  expect_true(all(is.finite(res_flat[["value"]])))

  zero_data <- single_time_data |> 
    dplyr::mutate(truth_value = 0.0)
  res_zero <- estimate_true_selectivity(data = zero_data, ages = true_ages, functional_form = "logistic")
  #' @description Test that data arrays consisting of absolute zeros do not trigger optimization collapses.
  expect_true(all(is.finite(res_zero[["value"]])))

  min_groups_data <- single_time_data |> 
    dplyr::filter(truth_group %in% c("age1", "age2"))
  res_min <- estimate_true_selectivity(data = min_groups_data, ages = true_ages[1:2], functional_form = "logistic")
  #' @description Test that the function completes parameter extractions given minimum required age groups (exactly 2).
  expect_equal(object = nrow(res_min), expected = 2)
})

## Error handling ----
test_that("estimate_true_selectivity() returns predictable structural error catch breaks", {
  #' @description Test that a data frame or tibble format validation step trips on raw matrix or arrays.
  expect_error(
    object = estimate_true_selectivity(data = as.matrix(synthetic_data)),
    regexp = "must be a tibble"
  )

  #' @description Test that an immediate failure flags out empty user rows.
  expect_error(
    object = estimate_true_selectivity(data = synthetic_data[0, ]),
    regexp = "cannot be empty"
  )

  #' @description Test that validation fails if required structural identifiers like truth_value are omitted.
  expect_error(
    object = estimate_true_selectivity(data = dplyr::select(synthetic_data, -truth_value)),
    regexp = "is missing required column"
  )

  multi_species_data <- synthetic_data
  multi_species_data[["species_name"]][1:4] <- "Haddock"

  #' @description Test that a clear warning is triggered when un-filtered multi-species data is evaluated.
  expect_error(
    object = estimate_true_selectivity(data = multi_species_data, ages = true_ages),
    regexp = "contains multiple species"
  )

  #' @description Test that parsing aborts if the functional groups lack enough variation to fit a continuous curve.
  expect_error(
    object = estimate_true_selectivity(
      data = dplyr::filter(synthetic_data, truth_group == "age1"), 
      ages = true_ages
    ),
    regexp = "must contain at least 2 unique groups"
  )

  #' @description Test that providing an unnamed age map vector returns a structured argument error.
  expect_error(
    object = estimate_true_selectivity(data = synthetic_data, ages = c(1, 2, 3, 4)),
    regexp = "must be a \\*\\*named\\*\\* numeric vector"
  )

  #' @description Test that providing an incomplete age map vector flags the missing specific group names.
  expect_error(
    object = estimate_true_selectivity(data = synthetic_data, ages = c("age1" = 1, "age2" = 2)),
    regexp = "Missing explicit age assignments"
  )

  #' @description Test that non-increasing or non-monotonic mapped numeric target systems fail structural checks.
  expect_error(
    object = estimate_true_selectivity(data = synthetic_data, ages = c("age1" = 1, "age2" = 1, "age3" = 3, "age4" = 4)),
    regexp = "must layout in a strictly increasing sequence"
  )
})
