# Instructions ----
#' This file follows the format generated by ecosystemdata:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemdata:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# Setup ----
# Load or prepare any necessary data for testing
data <- ecosystemdata::ewe_nwatlantic_base
data(ewe_nwatlantic_base, package = "ecosystemdata")
data <- ewe_nwatlantic_base
ewe_nwatlantic_base |> dplyr::filter(year == 2007)

# calc_truth_biomass ----
## IO correctness ----
test_that("calc_truth_biomass() works with correct inputs", {
  biomass <- calc_truth(
    data, 
    stock_name = "AtlanticMenhaden"
  )

  biomass 
  biomass |> tidyr::unnest(truth_om) |> print(n = 1300)
  
  #' @description Test that calc_truth_biomass(x) returns y.
  expect_equal(
    object = calc_truth_biomass(x),
    expected = y
  )

  #' @description Test that calc_truth_biomass(x) returns y.
  expect_equal(
    object = calc_truth_biomass(x),
    expected = y
  )
})

## Edge handling ----
test_that("calc_truth_biomass() returns correct outputs for edge cases", {
  #' @description Test that calc_truth_biomass(x) returns an error.
  expect_error(
    object = calc_truth_biomass(x)
  )
})

## Error handling ----
test_that("calc_truth_biomass() returns correct error messages", {
  #' @description Test that calc_truth_biomass(x) returns expected error.
  expect_error(
    object = calc_truth_biomass(x),
    regexp = "Insert text here that should be in the error message."
  )
})
