# Instructions ----
#' This file follows the format generated by ecosystemom:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemom:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# Setup ----
# Path to real data for testing
ewe_ecosim_base_nwatlantic_path <- system.file(
  "extdata", "ewe_ecosim_base_nwatlantic",
  package = "ecosystemom"
)
if (ewe_ecosim_base_nwatlantic_path == "") {
  ewe_ecosim_base_nwatlantic_path <- file.path(
    "inst", "extdata", "ewe_ecosim_base_nwatlantic"
  )
}

# Load functional groups for use in tests
functional_groups <- get_functional_groups(
  file_path = fs::path(ewe_ecosim_base_nwatlantic_path, "basic_estimates.csv")
)

model_years <- 1985:2017

# load_model ----
## IO correctness ----
test_that("load_model() works with correct inputs for ewe_ecosim", {
  #' @description Test that load_model() for ewe_ecosim returns a tibble.
  ewe_model <- load_model(
    directory = ewe_ecosim_base_nwatlantic_path,
    functional_groups = functional_groups,
    type = "ewe_ecosim",
    verbose = FALSE
  )
  expect_true(tibble::is_tibble(ewe_model))

  #' @description Test that load_model() for ewe_ecosim returns correct columns.
  # Note: 'fleet' and 'reference' are not always present, so not checked here.
  expect_equal(
    object = colnames(ewe_model),
    expected = c(
      "file_name", "type", "year", "month", "functional_group", "value", 
      "species", "group", "functional_group_snake_case", "unit"
    )
  )

  expect_equal(
    object = ewe_model |> 
      dplyr::pull(year) |>
      unique() |>
      sort(),
    expected = model_years
  )

  #' @description Test that load_model() for ewe_ecosim returns correct types.
  expected_types <- c(
    "biomass", "catch", "fishing_mortality", "natural_mortality", 
    "total_mortality", "weight"
  )
  expect_equal(
    object = sort(unique(ewe_model[["type"]])),
    expected = sort(expected_types)
  )

  #' @description Test that load_model() respects custom units.
  ewe_model_custom_unit <- load_model(
    directory = ewe_ecosim_base_nwatlantic_path,
    functional_groups = functional_groups,
    type = "ewe_ecosim",
    unit = c(
      "biomass" = "mt",
      "catch" = "mt",
      "landings" = "mt",
      "total_mortality" = "year^-1",
      "weight" = "kg"
    ),
    verbose = FALSE
  )
  
  expect_equal(
    object = ewe_model_custom_unit |> 
      dplyr::filter(type == "weight") |> 
      dplyr::pull(unit) |> 
      unique(),
    expected = "kg"
  )
})


## Edge handling ----
test_that("load_model() returns correct outputs for edge cases", {
  #' @description Test that load_model() without functional_groups returns an error.
  expect_error(
    object = load_model(
      directory = ewe_ecosim_base_nwatlantic_path,
      type = "ewe_ecosim"
    ),
    regexp = "is missing, with no default"
  )
  #' @description Test that load_model() without directory returns an error.
  expect_error(
    object = load_model(
      functional_groups = functional_groups,
      type = "ewe_ecosim"
    )
  )
})

## Error handling ----
test_that("load_model() returns correct error messages", {
  #' @description Test that load_model() with an invalid type returns an error.
  expect_error(
    object = load_model(type = "invalid_type"),
    regexp = "must be one of"
  )
  #' @description Test that load_model() for atlantis returns a 'not configured' error.
  expect_error(
    object = load_model(type = "atlantis"),
    regexp = "is not yet configured for"
  )
})

test_that("load_model_ewe_ecosim() returns correct error messages", {
  withr::with_tempdir({
    # Create a dummy functional groups data frame
    functional_groups <- data.frame(
      functional_group = c("group1", "group2"),
      stringsAsFactors = FALSE
    )

    #' @description Test that load_model_ewe_ecosim() errors when files are missing.
    expect_error(
      load_model_ewe_ecosim(
        directory = ".",
        functional_groups = functional_groups,
        verbose = FALSE
      ),
      "Missing required files"
    )
  })
})
