# Instructions ----
#' This file follows the format generated by ecosystemom:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemom:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# Setup ----
# Load or prepare any necessary data for testing
expected_error_message_positive <- "must be a positive numeric vector"
expected_error_message_with_zero <- "must be a non-negative numeric vector"
expected_error_message_sample_size <- "must be a single positive integer"

# sample_lognormal ----
## IO correctness ----
test_that("sample_lognormal() works with correct inputs", {
  #' @description Test that sample_lognormal(1, 1) returns known result when
  #' the seed is set to a defined value of 123.
  set.seed(123)
  expect_equal(
    object = sample_lognormal(1, 1),
    expected = 0.346291059
  )

  #' @description Test that sample_lognormal(1) returns two different values
  #' when the seed is not set.
  expect_false(
    sample_lognormal(1) == sample_lognormal(1)
  )

  x <- 1:5
  #' @description Test that sample_lognormal() returns the input values when
  #' the standard deviation is set to zero.
  expect_equal(
    sample_lognormal(x, sd = 0),
    x
  )

  set.seed(1)
  #' @description Test that sample_lognormal() returns the correct values when
  #' the standard deviation is zero and a positive value. This test was created
  #' to ensure that the inputs are duplicated in the correct way as part of a
  #' bug found in [PR #2](https://github.com/NOAA-FIMS/ecosystemom/pull/2).
  expect_equal(
    sample_lognormal(1, sd = c(0, 1)),
    c(1.0000000, 0.324180827)
  )
})

## Edge handling ----
test_that("sample_lognormal() returns correct outputs for edge cases", {
  #' @description Test that sample_lognormal() returns a vector when a vector
  #' is passed to `x` but a single value is passed to `sd`.
  expect_equal(
    object = length(sample_lognormal(1:5, 1)),
    expected = 5
  )

  #' @description Test that sample_lognormal() returns a vector when a single
  #' value is passed to `x` but a vector is passed to `sd`.
  expect_equal(
    object = length(sample_lognormal(1, 1:5)),
    expected = 5
  )

  #' @description Test that sample_lognormal() returns a valid answer when an
  #' integer is passed to `x`.
  expect_no_error(
    object = sample_lognormal(1L, 1)
  )

  #' @description Test that sample_lognormal() returns a valid answer when a
  #' double is passed to `x`.
  expect_no_error(
    object = sample_lognormal(1.0, 1)
  )
})

## Error handling ----
test_that("sample_lognormal() returns correct error messages", {
  #' @description Test that sample_lognormal() returns expected error when two
  #' different size vectors are passed.
  expect_error(
    object = sample_lognormal(1:5, 1:10),
    regexp = "Length of `x` and `sd` must be the same"
  )
  #' @description Test that sample_lognormal() returns expected error when
  #' a negative value is passed to `sd`.
  expect_error(
    object = sample_lognormal(1, -1),
    regexp = "All values of `sd` must be positive"
  )
})

# sample_gamma ----
## IO correctness ----
test_that("sample_gamma() works with correct inputs", {
  #' @description Test that sample_gamma(1, 1) returns a known result when the
  #' seed is set to a defined value of 123.
  set.seed(123)
  expect_equal(
    object = sample_gamma(1, 1),
    expected = 0.182217107
  )

  #' @description Test that sample_gamma(1) returns two different values when
  #' the seed is not set.
  expect_false(
    sample_gamma(1) == sample_gamma(1)
  )

  x <- 1:5
  #' @description Test that sample_gamma() returns the input values when the
  #' standard deviation is set to zero.
  expect_equal(
    sample_gamma(x, sd = 0),
    x
  )

  set.seed(1)
  #' @description Test that sample_gamma() returns the correct values when the
  #' standard deviation is zero and a positive value.
  expect_equal(
    sample_gamma(1, sd = c(0, 1)),
    c(1.0000000, 0.155141357)
  )
})

## Edge handling ----
test_that("sample_gamma() returns correct outputs for edge cases", {
  #' @description Test that sample_gamma() returns a vector when a vector is
  #' passed to `x` but a single value is passed to `sd`.
  expect_equal(
    object = length(sample_gamma(1:5, 1)),
    expected = 5
  )

  #' @description Test that sample_gamma() returns a vector when a single
  #' value is passed to `x` but a vector is passed to `sd`.
  expect_equal(
    object = length(sample_gamma(1, 1:5)),
    expected = 5
  )

  #' @description Test that sample_gamma() returns a valid answer when an
  #' integer is passed to `x`.
  expect_no_error(
    object = sample_gamma(1L, 1)
  )

  #' @description Test that sample_gamma() returns a valid answer when a
  #' double is passed to `x`.
  expect_no_error(
    object = sample_gamma(1.0, 1)
  )
})

## Error handling ----
test_that("sample_gamma() returns correct error messages", {
  #' @description Test that sample_gamma() returns expected error when two
  #' different size vectors are passed.
  expect_error(
    object = sample_gamma(1:5, 1:10),
    regexp = "Length of `x` and `sd` must be the same"
  )
  #' @description Test that sample_gamma() returns expected error when a
  #' negative value is passed to `sd`.
  expect_error(
    object = sample_gamma(1, -1),
    regexp = "All values of `sd` must be positive"
  )
  #' @description Test that sample_gamma() returns expected error when a
  #' negative value is passed to `x`.
  expect_error(
    object = sample_gamma(-1, 1),
    regexp = "All values of `x` must be non-negative"
  )
  #' @description Test that sample_gamma() returns expected error when a
  #' zero value is passed to `x` and a positive value is passed to `sd`.
  expect_error(
    object = sample_gamma(0, 1),
    regexp = "Values of `x` must be positive when `sd` is greater than zero"
  )
})

# sample_multinomial ----
## IO correctness ----
test_that("sample_multinomial() works with correct inputs", {
  #' @description Test that sample_multinomial(1, 1) returns known result when
  #' the seed is set to a defined value of 123.
  set.seed(123)
  expect_equal(
    object = sample_multinomial(1, 1),
    expected = 1
  )

  #' @description Test that sample_multinomial(x) returns two different values
  #' when the seed is not set.
  expect_false(all(
    sample_multinomial(c(1, 1), 10) == sample_multinomial(c(1, 1), 10)
  ))
})

## Edge handling ----
test_that("sample_multinomial() returns correct outputs for edge cases", {
  #' @description Test that sample_multinomial(x) returns a valid answer when an
  #' integer is passed to `x`.
  expect_no_error(
    object = sample_multinomial(1L, 1)
  )

  #' @description Test that sample_multinomial(x) returns a valid answer when a
  #' double is passed to `x`.
  expect_no_error(
    object = sample_multinomial(1.0, 1)
  )

  #' @description Test that sample_multinomial(x) returns a valid answer when a
  #' vector of proportions is passed to `x`.
  set.seed(1)
  expect_equal(
    object = sample_multinomial(c(0.2, 0.4, 0.4), 3),
    expected = c(0, 1, 2)
  )

  #' @description Test that sample_multinomial(x) returns a valid answer when a
  #' vector of proportions is passed to `x` that does not sum to one.
  set.seed(1)
  expect_equal(
    object = sample_multinomial(c(0.2, 0.4), 3),
    expected = c(0, 3)
  )

  #' @description Test that sample_multinomial(x) returns a valid answer when a
  #' vector that includes zeros is passed to `x`.
  set.seed(1)
  expect_equal(
    object = sample_multinomial(c(1, 0, 5), sample_size = 10),
    expected = c(1, 0, 9)
  )
})

## Error handling ----
test_that("sample_multinomial() returns correct error messages", {
  #' @description Test that sample_multinomial() returns expected error when
  #' negative values are passed to `x`.
  expect_error(
    object = sample_multinomial(-2:0, 20),
    regexp = expected_error_message_with_zero
  )
  #' @description Test that sample_multinomial() returns expected error when
  #' a data frame is passed to `x`.
  expect_error(
    object = sample_multinomial(as.data.frame(1:10), 20),
    regexp = expected_error_message_with_zero
  )
  #' @description Test that sample_multinomial() returns expected error when
  #' a empty vectors are passed to `x` and `sample_size`.
  expect_error(
    object = sample_multinomial(x = vector(), integer()),
    regexp = expected_error_message_with_zero
  )
  #' @description Test that sample_multinomial(x) returns expected error when a
  #' vector of all zeros is passed to `x`.
  expect_error(
    object = sample_multinomial(c(0, 0), 10),
    regexp = expected_error_message_with_zero
  )
  #' @description Test that sample_multinomial() returns expected error when
  #' more than one value is passed to `sample_size`.
  expect_error(
    object = sample_multinomial(1, 1:10),
    regexp = expected_error_message_sample_size
  )
  #' @description Test that sample_multinomial() returns expected error when
  #' a negative value is passed to `sample_size`.
  expect_error(
    object = sample_multinomial(1, -1),
    regexp = expected_error_message_sample_size
  )
})

# sample_dirichlet_multinomial ----
## IO correctness ----
test_that("sample_dirichlet_multinomial() works with correct inputs", {
  #' @description Test that sample_dirichlet_multinomial(1, 1) returns known
  #' result when the seed is set to a defined value of 123.
  set.seed(123)
  expect_equal(
    object = sample_dirichlet_multinomial(1, 1),
    expected = 1
  )

  #' @description Test that sample_dirichlet_multinomial(x) returns two
  #' different values when the seed is not set.
  expect_false(all(
    sample_dirichlet_multinomial(c(1, 1), 10) ==
      sample_dirichlet_multinomial(c(1, 1), 10)
  ))

  #' @description Test that sample_dirichlet_multinomial(x, sample_size)
  #' returns the same output as sample_multinomial(x, sample_size) when they are
  #' passed the same inputs.
  set.seed(123)
  x_inputs <- c(100000000000, 0, 30000000000)
  x <- sample_dirichlet_multinomial(x_inputs, sample_size = 4)
  set.seed(123)
  y <- sample_multinomial(x_inputs, sample_size = 4)
  expect_equal(object = x, expected = y)
})

## Edge handling ----
test_that("sample_dirichlet_multinomial() returns correct outputs for edge cases", {
  #' @description Test that sample_dirichlet_multinomial(x) returns a valid
  #' answer when an integer is passed to `x`.
  expect_no_error(
    object = sample_dirichlet_multinomial(1L, 1)
  )

  #' @description Test that sample_dirichlet_multinomial(x) returns a valid
  #' answer when a double is passed to `x`.
  expect_no_error(
    object = sample_dirichlet_multinomial(1.0, 1)
  )

  #' @description Test that sample_dirichlet_multinomial(x) returns a valid
  #' answer when a vector of proportions is passed to `x`.
  set.seed(1)
  expect_equal(
    object = sample_dirichlet_multinomial(c(0.2, 0.4, 0.4), 3),
    expected = c(0, 2, 1)
  )

  #' @description Test that sample_dirichlet_multinomial(x) returns a valid
  #' answer when a vector of proportions is passed to `x` that does not sum to
  #' one.
  set.seed(1)
  expect_equal(
    object = sample_dirichlet_multinomial(c(0.2, 0.4), 3),
    expected = c(0, 3)
  )

  #' @description Test that sample_dirichlet_multinomial(x) returns a valid
  #' answer when a vector that includes zeros is passed to `x`.
  set.seed(1)
  expect_equal(
    object = sample_dirichlet_multinomial(c(1, 0, 5), sample_size = 10),
    expected = c(1, 0, 9)
  )
})

## Error handling ----
test_that("sample_dirichlet_multinomial() returns correct error messages", {
  #' @description Test that sample_dirichlet_multinomial() returns expected
  #' error when negative values are passed to `x`.
  expect_error(
    object = sample_dirichlet_multinomial(-2:0, 20),
    regexp = expected_error_message_with_zero
  )
  #' @description Test that sample_dirichlet_multinomial() returns expected
  #' error when a data frame is passed to `x`.
  expect_error(
    object = sample_dirichlet_multinomial(as.data.frame(1:10), 20),
    regexp = expected_error_message_with_zero
  )
  #' @description Test that sample_dirichlet_multinomial() returns expected
  #' error when a empty vectors are passed to `x` and `sample_size`.
  expect_error(
    object = sample_dirichlet_multinomial(x = vector(), integer()),
    regexp = expected_error_message_with_zero
  )
  #' @description Test that sample_multinomial(x) returns expected error when a
  #' vector of all zeros is passed to `x`.
  expect_error(
    object = sample_dirichlet_multinomial(c(0, 0), 10),
    regexp = expected_error_message_with_zero
  )
  #' @description Test that sample_dirichlet_multinomial() returns expected
  #' error when more than one value is passed to `sample_size`.
  expect_error(
    object = sample_dirichlet_multinomial(1, 1:10),
    regexp = expected_error_message_sample_size
  )
  #' @description Test that sample_dirichlet_multinomial() returns expected
  #' error when a negative value is passed to `sample_size`.
  expect_error(
    object = sample_dirichlet_multinomial(1, -1),
    regexp = expected_error_message_sample_size
  )
})
