# Instructions ----
#' This file follows the format generated by ecosystemom:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemom:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# split_functional_groups ----
## IO correctness ----
test_that("split_functional_groups() works with correct inputs", {
  #' @description Test that split_functional_groups(x) returns a tibble.
  expect_equal(
    object = split_functional_groups(c("spiny dogfish0", "spiny dogfish 2")),
    expected = tibble::tibble(
      functional_group = c("spiny dogfish0", "spiny dogfish 2"),
      species = c("spiny dogfish", "spiny dogfish"),
      group = c("0", "2"),
      functional_group_snake_case = c("spiny_dogfish_0", "spiny_dogfish_2")
    )
  )

  #' @description Test that split_functional_groups(x), where the third row of
  #' x contains a `+` without any digits signifying a plus groups returns a
  #' row with + as the group.
  expect_equal(
    object = split_functional_groups(c(
      "spiny dogfish 0",
      "spiny dogfish 1-2",
      "spiny dogfish +",
      "apple"
    )),
    expected = tibble::tibble(
      functional_group = c(
        "spiny dogfish 0",
        "spiny dogfish 1-2",
        "spiny dogfish +",
        "apple"
      ),
      species = c(
        "spiny dogfish",
        "spiny dogfish",
        "spiny dogfish",
        "apple"
      ),
      group = c("0", "1-2", "+", NA_character_),
      functional_group_snake_case = c(
        "spiny_dogfish_0",
        "spiny_dogfish_1_2",
        "spiny_dogfish_plus",
        "apple"
      )
    )
  )

  #' @description Test that parenthesized age/group suffixes are parsed
  #' correctly and parentheses are ignored for species/group splitting.
  expect_equal(
    object = split_functional_groups(c(
      "King mackerel (0-1yr)",
      "King mackerel_(0-1yr)",
      "King mackerel (1+yr)"
    )),
    expected = tibble::tibble(
      functional_group = c(
        "King mackerel (0-1yr)",
        "King mackerel_(0-1yr)",
        "King mackerel (1+yr)"
      ),
      species = rep("King mackerel", 3),
      group = c("0-1yr", "0-1yr", "1+yr"),
      functional_group_snake_case = c(
        "king_mackerel_0_1yr",
        "king_mackerel_0_1yr",
        "king_mackerel_1_plusyr"
      )
    )
  )
})

## Edge handling ----
test_that("split_functional_groups() returns correct outputs for edge cases", {
  input <- c("SpinyDogfish0", "SpinyDogfish 2_3")
  test <- split_functional_groups(input)
  #' @description Test that split_functional_groups(x) uses sentence case rather
  #' than camel case.
  expect_equal(
    object = test[["species"]],
    expected = c("Spiny Dogfish", "Spiny Dogfish")
  )
  #' @description Test that split_functional_groups(x) returns the input values
  #' in the `"functional_group"` column.
  expect_equal(
    object = test[["functional_group"]],
    expected = input
  )

  #' @description Test that common two-word or three-word functional groups are
  #' not split into species/group unless they contain an explicit suffix.
  expect_equal(
    object = split_functional_groups(c(
      "Coastal dolphins",
      "Sea turtle",
      "Large coastal sharks",
      "Other tunas",
      "Other snapper",
      "Sea trout",
      "Oceanic piscivores",
      "Benthic piscivores",
      "Reef piscivores",
      "Reef invertebrate feeders",
      "Benthic coastal invertebrate feeders",
      "Coastal omnivores",
      "Reef omnivores",
      "Large oceanic planktivores",
      "Skates-rays"
    )),
    expected = tibble::tibble(
      functional_group = c(
        "Coastal dolphins",
        "Sea turtle",
        "Large coastal sharks",
        "Other tunas",
        "Other snapper",
        "Sea trout",
        "Oceanic piscivores",
        "Benthic piscivores",
        "Reef piscivores",
        "Reef invertebrate feeders",
        "Benthic coastal invertebrate feeders",
        "Coastal omnivores",
        "Reef omnivores",
        "Large oceanic planktivores",
        "Skates-rays"
      ),
      species = c(
        "Coastal dolphins",
        "Sea turtle",
        "Large coastal sharks",
        "Other tunas",
        "Other snapper",
        "Sea trout",
        "Oceanic piscivores",
        "Benthic piscivores",
        "Reef piscivores",
        "Reef invertebrate feeders",
        "Benthic coastal invertebrate feeders",
        "Coastal omnivores",
        "Reef omnivores",
        "Large oceanic planktivores",
        "Skates-rays"
      ),
      group = rep(NA_character_, 15),
      functional_group_snake_case = c(
        "coastal_dolphins",
        "sea_turtle",
        "large_coastal_sharks",
        "other_tunas",
        "other_snapper",
        "sea_trout",
        "oceanic_piscivores",
        "benthic_piscivores",
        "reef_piscivores",
        "reef_invertebrate_feeders",
        "benthic_coastal_invertebrate_feeders",
        "coastal_omnivores",
        "reef_omnivores",
        "large_oceanic_planktivores",
        "skates_rays"
      )
    )
  )
})

## Error handling ----
test_that("split_functional_groups() returns correct error messages", {
  #' @description Test that split_functional_groups(x) returns expected error.
  expect_error(
    object = split_functional_groups(data.frame(functional_groups = "x")),
    regexp = "must be a character vector"
  )

  #' @description Test that split_functional_groups(x) requires input.
  expect_error(
    object = split_functional_groups(),
    regexp = "argument \"x\" is missing, with no default"
  )

  #' @description Test that non-numeric characters lead to an error but that
  #' a plus sign, a minus sign, or an underscore are okay. The dollar sign at
  #' the end of the regular expression ensures that the error message only contains
  #' the first functional group, which is the only invalid one.
  expect_error(
    object = split_functional_groups(c("sdog#", "spiny+", "s_dog", "s-dog")),
    regexp = "`sdog#`$"
  )
  #' @description Test that you cannot have an ampersand.
  expect_error(
    object = split_functional_groups(c("spiny & dog")),
    regexp = "cannot contain non alpha-numerics except \\+, -, _, \\(, or \\)"
  )

  #' @description Test that split_functional_groups(x) requires unique input.
  expect_error(
    object = split_functional_groups(c("a", "a")),
    regexp = "must be unique functional groups"
  )
})
