# Instructions ----
#' This file follows the format generated by ecosystemom:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemom:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# get_truth ----
## Setup ----
# Load or prepare any necessary data for testing
data(ewe_ecosim_base_nwatlantic, package = "ecosystemom")
data <- ecosystemom::ewe_ecosim_base_nwatlantic

expected_truth_label <- c(
  "biomass", "catch", "fishing_mortality", "natural_mortality", "numbers",
  "total_mortality", "weight"
)
expected_truth_type <- c("index", "agecomp")
expected_truth_time_step <- c("monthly", "yearly")

## IO correctness ----
test_that("get_truth() works with correct inputs", {
  expected_species_name <- "menhaden"

  truth <- get_truth(
    data,
    species_name = expected_species_name
  ) |>
    tidyr::unnest(cols = c(truth_om))

  #' @description Test that get_truth() returns a nested data with the correct column names.
  expect_equal(
    object = colnames(truth),
    expected = c(
      "species_name",
      "truth_label",
      "truth_type",
      "truth_time_step",
      "truth_year",
      "truth_month",
      "truth_unit",
      "truth_value",
      "truth_group"
    )
  )

  #' @description Test that get_truth() returns correct species_name values.
  expect_equal(
    object = unique(truth[["species_name"]]),
    expected = expected_species_name
  )

  #' @description Test that get_truth() returns correct truth_label values.
  expect_equal(
    object = unique(truth[["truth_label"]]),
    expected = expected_truth_label
  )

  #' @description Test that get_truth() returns correct truth_type values.
  expect_equal(
    object = unique(truth[["truth_type"]]),
    expected = expected_truth_type
  )

  #' @description Test that get_truth() returns correct truth_time_step values.
  expect_equal(
    object = unique(truth[["truth_time_step"]]),
    expected = expected_truth_time_step
  )

  # Extract yearly truth values
  truth_yearly <- truth |>
    dplyr::filter(truth_time_step == "yearly") |>
    dplyr::select(-c(truth_time_step, truth_month)) |>
    dplyr::relocate(truth_value, .after = truth_group) |>
    dplyr::arrange(truth_label, truth_type, truth_year, truth_group)

  # Compute the mean of monthly values for comparison
  mean_truth_monthly <- truth |>
    dplyr::filter(truth_time_step == "monthly") |>
    dplyr::group_by(
      species_name, truth_label, truth_type, truth_year, truth_unit, truth_group
    ) |>
    dplyr::summarise(
      truth_value = mean(truth_value, na.rm = TRUE),
      .groups = "drop"
    ) |>
    dplyr::arrange(
      truth_label, truth_type, truth_year, truth_unit, truth_group
    )

  #' @description Test that yearly output from get_truth matches the averaged monthly output.
  expect_equal(
    object = truth_yearly,
    expected = mean_truth_monthly
  )
})

## Edge handling ----
test_that("get_truth() output can be bound", {
  expected_species_names <- c("striped bass", "bluefish")
  truth <- purrr::map_dfr(
    expected_species_names,
    function(x) get_truth(data, species_name = x)
  )

  n_species <- length(expected_species_names)
  # All labels with index type
  n_label_index <- sum(!(expected_truth_label %in% c("weight", "natural_mortality", "total_mortality")))
  # All labels with agecomp type
  n_label_agecomp <- length(expected_truth_label)
  n_time_step <- length(expected_truth_time_step)

  expected_nrow <- n_species * (
    (n_label_index * n_time_step) +
      (n_label_agecomp * n_time_step)
  )
  #' @description Test that combined truth from multiple species has the expected number of rows.
  expect_equal(
    object = nrow(truth),
    expected = expected_nrow
  )
})

test_that("get_truth() returns correct outputs for edge cases", {
  #' @description Test that get_truth() returns NAs for 'group' when the species does not have multiple groups.
  truth <- get_truth(
    data,
    species_name = "anchovies"
  ) |>
    tidyr::unnest(cols = c(truth_om))
  expect_equal(
    object = unique(truth[["truth_group"]]),
    expected = NA_character_
  )
})

## Error handling ----
test_that("get_truth() returns correct error messages", {
  #' @description Test that get_truth() returns error if an unknown species_name is provided.
  expect_error(
    object = get_truth(data = data, species_name = "nonexistent_species"),
    regexp = "not found in the unique(*)"
  )

  data_missing_biomass <- data |>
    dplyr::filter(species == "menhaden" & type != "biomass")
  data_missing_weight <- data |>
    dplyr::filter(species == "menhaden" & type != "weight")
  #' @description Test that get_truth() returns error if biomass is missing.
  expect_error(
    object = get_truth(data = data_missing_biomass, species_name = "menhaden"),
    regexp = "at-age data is missing"
  )

  #' @description Test that get_truth() returns error if weight is missing.
  expect_error(
    object = get_truth(data = data_missing_weight, species_name = "menhaden"),
    regexp = "at-age data is missing"
  )
})
