# Instructions ----
#' This file follows the format generated by ecosystemom:::use_testthat_template().
#' Necessary tests include input and output (IO) correctness [IO
#' correctness], edge-case handling [Edge handling], and built-in errors and
#' warnings [Error handling]. See `?ecosystemom:::use_testthat_template` for more
#' information. Every test should have a @description tag that takes up just
#' one line, which will be used in the bookdown report of {testthat} results.

# Setup ----

# IO correctness ----
test_that("create_dsem_inputs() works with correct inputs", {
  withr::with_tempdir({
    # Mock data for data_om
    data_om <- tibble::tibble(
      year = rep(1984, 2),
      month = rep(1, 2),
      functional_group = c("Phytoplankton", "Menhaden (0yr)"),
      functional_group_snake_case = c("phytoplankton", "menhaden_0yr"),
      type = "biomass",
      value = c(100, 50)
    )

    # Mock data for data_environment
    data_environment <- tibble::tibble(
      index = "amo",
      year = 1984,
      month = 1,
      value = 0.679,
      unit = "NA",
      lag_months = 1,
      impacted_group = "Menhaden (0yr)",
      impacted_group_snake_case = "menhaden_0yr"
    )

    # Mock data for data_diet_composition
    data_diet_composition <- tibble::tibble(
      prey = "Phytoplankton",
      predator = "Menhaden (0yr)",
      proportion = 0.5,
      prey_snake_case = "phytoplankton",
      predator_snake_case = "menhaden_0yr"
    )

    data <- tibble::tibble(
      data_om = list(data_om),
      data_environment = list(data_environment),
      data_diet_composition = list(data_diet_composition)
    )

    #' @description Test that create_dsem_inputs() works with mock data.
    result <- create_dsem_inputs(data, "Menhaden (0yr)", 0.1)
    expect_true(tibble::is_tibble(result))
    expect_equal(nrow(result), 1)
    expect_equal(
      colnames(result),
      c("data_time_series_all", "data_time_series_sem", "sem_tibble", "sem_lines")
    )
    expect_true(grepl("amo -> menhaden_0yr, 1, amo_menhaden_0yr", result[["sem_lines"]]))
    expect_true(grepl("phytoplankton -> menhaden_0yr, 0, phytoplankton_menhaden_0yr", result[["sem_lines"]]))
  })
})

test_that("create_dsem_inputs works with real data", {
  withr::with_tempdir({
    data_path <- system.file(
      "extdata", "ewe_ecosim_with_environmental_data_nwatlantic",
      package = "ecosystemom"
    )
    if (data_path == "") {
      data_path <- file.path(
        "inst", "extdata", "ewe_ecosim_with_environmental_data_nwatlantic"
      )
    }
    # Load functional groups
    functional_groups <- get_functional_groups(
      file_path = file.path(data_path, "basic_estimates.csv")
    )
    # Load EwE model output
    data_om <- load_model(
      directory = data_path,
      type = "ewe_ecosim",
      functional_groups = functional_groups,
      verbose = FALSE
    )

    # Load environmental data (AMO and PDSI indices)
    amo_path <- fs::path(
      data_path, "amo_lag1.csv"
    )
    amo_data <- read.csv(amo_path)

    # Read in palmer_drought_severity_index.csv
    pdsi_path <- fs::path(
      data_path, "pdsi_lag0.csv"
    )
    pdsi_data <- read.csv(pdsi_path)

    data_environment <- load_csv_environmental_data(
      file_path = amo_path,
      lag_months = 12,
      impacted_group = "menhaden 0"
    ) |>
      dplyr::bind_rows(
        load_csv_environmental_data(
          file_path = pdsi_path,
          lag_months = 0,
          impacted_group = "phytoplankton"
        )
      )

    # Load static diet composition data
    data_diet_composition <- load_diet_composition(
      file_path = fs::path(data_path, "diet_composition.csv"),
      verbose = FALSE
    )

    data <- tibble::tibble(
      data_om = list(data_om),
      data_environment = list(data_environment),
      data_diet_composition = list(data_diet_composition)
    )

    #' @description Test that create_dsem_inputs() works with real data files.
    result <- create_dsem_inputs(data, "menhaden 0", 0.05)
    expect_true(tibble::is_tibble(result))
    expect_equal(nrow(result), 1)
    expect_true(grepl("amo -> menhaden_0, 12, amo_menhaden_0", result[["sem_lines"]]))
    expect_true(grepl("pdsi -> phytoplankton, 0, pdsi_phytoplankton", result[["sem_lines"]]))
    expect_true(grepl("detritus -> menhaden_0, 0, detritus_menhaden_0", result[["sem_lines"]]))
    expect_true(grepl("striped_bass_2_5 -> menhaden_0, 0, striped_bass_2_5_menhaden_0", result[["sem_lines"]]))
  })
})


test_that("create_sem_equations() works with correct inputs", {
  #' @description Test that create_sem_equations() works with a valid tibble.
  sem_tibble <- tibble::tibble(
    driver = "sst",
    target = "menhaden_0yr",
    lag = 12,
    param_name = "sst_menhaden_0yr"
  )
  result <- create_sem_equations(sem_tibble)
  expect_type(result, "character")
  expect_equal(result, "sst -> menhaden_0yr, 12, sst_menhaden_0yr")
})

# Edge handling ----
test_that("create_dsem_inputs() handles edge cases", {
  #' @description Test create_dsem_inputs() with missing data components.
  data_om <- tibble::tibble(
    year = 1984, month = 1, functional_group = "A",
    functional_group_snake_case = "a", type = "biomass", value = 1
  )
  data <- list(data_om = list(data_om)) # Missing environment and diet data
  result <- create_dsem_inputs(data, "A")
  expect_equal(result[["sem_lines"]], "")
  expect_equal(nrow(result[["sem_tibble"]][[1]]), 0)

  #' @description Test create_dsem_inputs() with diet threshold that excludes all links.
  data_diet_composition <- tibble::tibble(
    prey = "B", predator = "A", proportion = 0.05,
    prey_snake_case = "b", predator_snake_case = "a"
  )
  data <- list(
    data_om = list(data_om),
    data_diet_composition = list(data_diet_composition)
  )
  result <- create_dsem_inputs(data, "A", diet_composition_threshold = 0.1)
  expect_equal(result[["sem_lines"]], "")
})

test_that("create_dsem_inputs() works with vector thresholds", {
  data_om <- tibble::tibble(
    year = rep(1984, 4),
    month = rep(1, 4),
    functional_group = c("Phytoplankton", "Zooplankton", "Menhaden (0yr)", "Striped Bass"),
    functional_group_snake_case = c("phytoplankton", "zooplankton", "menhaden_0yr", "striped_bass"),
    type = "biomass",
    value = c(20, 50, 80, 100)
  )

  data_diet_composition <- tibble::tibble(
    prey = c("Phytoplankton", "Zooplankton", "Menhaden (0yr)"),
    predator = c("Menhaden (0yr)", "Menhaden (0yr)", "Striped Bass"),
    proportion = c(0.5, 0.4, 0.8),
    prey_snake_case = c("phytoplankton", "zooplankton", "menhaden_0yr"),
    predator_snake_case = c("menhaden_0yr", "menhaden_0yr", "striped_bass")
  )

  data <- tibble::tibble(
    data_om = list(data_om),
    data_diet_composition = list(data_diet_composition)
  )

  #' @description Test create_dsem_inputs() with vector of focal groups and thresholds.
  result <- create_dsem_inputs(
    data,
    focal_functional_groups = c("Menhaden (0yr)", "Striped Bass"),
    diet_composition_threshold = c(0.45, 0.7)
  )

  # Phytoplankton (0.5) should be included for Menhaden (0.45 threshold)
  expect_true(grepl("phytoplankton -> menhaden_0yr", result[["sem_lines"]]))
  # Zooplankton (0.4) should be excluded for Menhaden (0.45 threshold)
  expect_false(grepl("zooplankton -> menhaden_0yr", result[["sem_lines"]]))
  # Menhaden (0.8) should be included for Striped Bass (0.7 threshold)
  expect_true(grepl("menhaden_0yr -> striped_bass", result[["sem_lines"]]))
  # Top-down link from Striped Bass to Menhaden should be present
  expect_true(grepl("striped_bass -> menhaden_0yr", result[["sem_lines"]]))
})

test_that("create_sem_equations() handles edge cases", {
  #' @description Test that create_sem_equations() handles an empty tibble.
  sem_tibble <- tibble::tibble(
    driver = character(),
    target = character(),
    lag = numeric(),
    param_name = character()
  )
  result <- create_sem_equations(sem_tibble)
  expect_equal(result, "")
})

# Error handling ----
test_that("create_sem() returns correct error messages", {
  #' @description Test create_dsem_inputs() errors with mismatched vector lengths for thresholds.
  expect_error(
    create_dsem_inputs(
      data = list(),
      focal_functional_groups = c("A", "B"),
      diet_composition_threshold = c(0.1, 0.2, 0.3)
    ),
    regexp = "If 'diet_composition_threshold' is a vector, its length must match the length of 'focal_functional_groups'."
  )
})
