utils::globalVariables(c(
  "truth_year",
  "truth_group",
  "truth_value",
  "model_family",
  "module_name",
  "fleet_name",
  "module_type",
  "label",
  "age",
  "length",
  "time",
  "value",
  "estimation_type",
  "distribution_type",
  "distribution",
  "variance",
  "varying"
))

#' Estimate true selectivity parameters from ecosystem model output
#'
#' @description
#' This function estimates selectivity curve parameters from ecosystem model fishing
#' mortality-at-age data. It fits the curves using a Gamma distribution likelihood
#' on un-normalized values to account for the mean-variance relationship.
#'
#' @param data A tibble containing filtered ecosystem model output for a single
#'   species, typically generated by calling [load_model()] followed by
#'   [get_truth()]. Must contain the columns:
#'   "species_name", "truth_label", "truth_type", "truth_time_step",
#'   "truth_group", "truth_year", "truth_unit", and "truth_value". The data should
#'   be pre-filtered to a single species; if multiple species are detected in
#'   the data, an error is issued.
#' @param ages A **named numeric vector** where the names correspond exactly to the
#'   unique labels in the `truth_group` column from `data`, and the values
#'   represent the actual structural or representative midpoint ages.
#'
#'   For example: `ages = c("0" = 0, "1" = 1, "2+" = 2)` or
#'   `ages = c("juvenile" = 1, "adult" = 4)`.
#'
#'   If `NULL` (default), the function will attempt to convert `truth_group` directly
#'   into numeric values. If that fails, it will fall back to sequential indexing
#'   and issue a warning.
#' @param functional_form A character string specifying the selectivity curve
#'   type. Currently supports "logistic" and "double_logistic".
#'
#' @return A tibble in NOAA-FIMS/FIMS format with the estimated parameter values.
#' @export
estimate_true_selectivity <- function(data,
                                      ages = NULL,
                                      functional_form = c("logistic", "double_logistic")) {
  # Validate inputs
  ages <- validate_data_and_ages(data, ages)

  # Ensure tracking order is strictly based on ascending age scale sorting
  sorted_age_mapping <- sort(ages)
  ordered_groups <- names(sorted_age_mapping)
  numeric_ages_vector <- unname(sorted_age_mapping)

  # Check structure metrics on the resolved numeric age vector
  if (is.unsorted(numeric_ages_vector, strictly = TRUE)) {
    cli::cli_abort("Resolved numeric age scales must layout in a strictly increasing sequence.")
  }

  # Determine unique time combinations based on truth_year
  time_combinations <- data |>
    dplyr::select(truth_year) |>
    dplyr::distinct()

  helper_function_name <- paste0("estimate_", functional_form, "_parameters")

  # Dynamic helper block rewritten using native tidyverse grouping
  results_yearly <- data |>
    # Group by year
    dplyr::group_by(truth_year) |>
    # Apply the estimation logic to each group block simultaneously
    dplyr::reframe(
      {
        # Figure out which groups actually exist for this specific year
        current_groups <- as.character(truth_group)
        # Extract and sort the corresponding true numeric ages for these groups
        current_age_mapping <- sort(sorted_age_mapping[current_groups])
        current_ordered_groups <- names(current_age_mapping)
        current_numeric_ages <- unname(current_age_mapping)
        # Align the truth values perfectly with the sorted ages
        # This matches the values to the sorted age order for this specific year
        data_vector <- truth_value[match(current_ordered_groups, current_groups)]
        # Run the helper function
        params <- do.call(
          helper_function_name,
          list(raw_values = data_vector, ages = current_numeric_ages)
        )
        # Return the parameters data frame directly inside summarize()
        params
      },
      .groups = "drop"
    ) |>
    dplyr::rename(
      time = truth_year
    ) |>
    dplyr::mutate(
      module_name = "Selectivity"
    ) |>
    dplyr::select(
      model_family, module_name, fleet_name, module_type, label,
      age, length, time, value,
      estimation_type, distribution_type, distribution
    )
  # Dynamically evaluate parameter variance across all years
  # Group by the parameter type ('label') to check if its values change over time
  is_time_varying <- results_yearly |>
    dplyr::group_by(label) |>
    dplyr::summarise(
      variance = if (dplyr::n() > 1) stats::var(value, na.rm = TRUE) else 0,
      .groups = "drop"
    ) |>
    dplyr::summarise(varying = any(variance > 1e-7, na.rm = TRUE)) |>
    dplyr::pull(varying)

  # Format the final output based on variance evaluation
  if (is_time_varying) {
    # Keep time-varying sequence format
    results <- results_yearly
  } else {
    # Collapse down to just one set of global parameters (e.g., 2 rows for logistic)
    results <- results_yearly |>
      dplyr::distinct(
        model_family, module_name, fleet_name, module_type, label,
        age, length,
        .keep_all = TRUE
      ) |>
      dplyr::mutate(time = NA_integer_)
  }
}

#' Estimate logistic curve parameters using Gamma Likelihood
#'
#' @description
#' This internal helper function fits a logistic curve to a vector of
#' observed values (e.g., fishing mortality) at different ages. The fitting is
#' performed by minimizing the negative log-likelihood of a Gamma distribution.
#'
#' @param raw_values A numeric vector of the observed values (e.g., fishing
#'   mortality) to which the curve will be fit. The order of this vector must
#'   correspond to the order of the `ages` vector.
#' @param ages A numeric vector of the ages corresponding to the `raw_values`.
#'   Must be sorted in ascending order.
#'
#' @return A tibble in a specific FIMS-like format containing the estimated
#'   parameters for the logistic curve (`inflection_point` and `slope`).
#' @noRd
estimate_logistic_parameters <- function(raw_values, ages) {
  # Define the objective function to be minimized (negative log-likelihood)
  objective_function_gamma <- function(parameters) {
    # Unpack parameters for the logistic model
    inflection_point <- parameters[1]
    slope <- parameters[2]
    # Asymptote is an internal scaling parameter for fitting, not part of the final output
    asymptote <- parameters[3]
    # Shape parameter (alpha) for the Gamma distribution
    shape <- parameters[4]

    # Calculate predicted values using the logistic function
    predicted <- asymptote / (1 + exp(-slope * (ages - inflection_point)))
    # Add a small epsilon to prevent log(0) issues in the likelihood calculation
    predicted <- pmax(predicted, 1e-4)

    # The scale parameter (beta) of the Gamma distribution is derived from mean (predicted) and shape
    scale_param <- predicted / shape
    # Return the negative log-likelihood; optim() minimizes this value
    -sum(stats::dgamma(raw_values, shape = shape, scale = scale_param, log = TRUE))
  }

  # Provide reasonable initial parameter estimates for the optimization
  max_val <- max(raw_values)
  # Initial guess for inflection point: the age closest to half the max value
  half_max_idx <- which.min(abs(raw_values - (max_val / 2)))
  initial_inflection <- if (length(half_max_idx) > 0) ages[half_max_idx] else stats::median(ages)

  # Perform the optimization using L-BFGS-B method which allows box constraints
  optimization_result <- stats::optim(
    # Initial parameter guesses: [inflection, slope, asymptote, shape]
    par = c(initial_inflection, 0.5, max_val, 2.0),
    fn = objective_function_gamma,
    method = "L-BFGS-B",
    # Lower and upper bounds for the parameters to ensure they are realistic
    lower = c(min(ages), 0.01, 1e-3, 0.1),
    upper = c(max(ages) + 1, 10, max_val * 2, 100)
  )

  # CRITICAL: We only format and return inflection_point and slope for FIMS.
  # The other parameters (asymptote, shape) were for fitting purposes only.
  tibble::tibble(
    model_family = "catch_at_age",
    module_name = NA_character_,
    fleet_name = NA_character_,
    module_type = "Logistic",
    label = c("inflection_point", "slope"),
    age = NA_real_,
    length = NA_real_,
    value = c(optimization_result[["par"]][1], optimization_result[["par"]][2]),
    estimation_type = "fixed_effects",
    distribution_type = NA_character_,
    distribution = NA_character_
  )
}

#' Estimate double logistic curve parameters using Gamma Likelihood
#'
#' @description
#' This internal helper function fits a double logistic curve, which
#' is often used to model selectivity that is dome-shaped (i.e., it increases
#' to a peak and then declines).
#'
#' @param raw_values A numeric vector of the observed values (e.g., fishing
#'   mortality) to which the curve will be fit. The order must match `ages`.
#' @param ages A numeric vector of the ages corresponding to `raw_values`, sorted
#'   in ascending order.
#'
#' @return A tibble in a specific FIMS-like format containing the four estimated
#'   parameters for the double logistic curve (`inflection_point_asc`, `slope_asc`,
#'   `inflection_point_desc`, `slope_desc`).
#' @noRd
estimate_double_logistic_parameters <- function(raw_values, ages) {
  # Define the objective function (negative Gamma log-likelihood)
  objective_function_gamma <- function(parameters) {
    # Unpack parameters for the double logistic model
    inflection_asc <- parameters[1]
    slope_asc <- parameters[2]
    inflection_desc <- parameters[3]
    slope_desc <- parameters[4]
    # Asymptote is an internal scaling parameter for fitting
    asymptote <- parameters[5]
    # Shape parameter (alpha) for the Gamma distribution
    shape <- parameters[6]

    # Calculate the ascending and descending limbs of the curve
    ascending <- 1 / (1 + exp(-slope_asc * (ages - inflection_asc)))
    descending <- 1 / (1 + exp(-slope_desc * (ages - inflection_desc)))
    # The full profile is the product of the ascending limb and (1 - descending limb)
    profile <- ascending * (1 - descending)

    # Normalize the profile and scale by the asymptote to get predicted values
    if (max(profile) > 0) {
      predicted <- asymptote * (profile / max(profile))
    } else {
      # If the profile is flat zero, avoid division by zero
      predicted <- rep(1e-4, length(ages))
    }
    # Add a small epsilon to prevent log(0) issues
    predicted <- pmax(predicted, 1e-4)

    # The scale parameter (beta) of the Gamma distribution
    scale_param <- predicted / shape
    # Return the negative log-likelihood
    -sum(stats::dgamma(raw_values, shape = shape, scale = scale_param, log = TRUE))
  }

  # Provide reasonable initial parameter estimates for the optimization
  max_idx <- which.max(raw_values)
  max_val <- raw_values[max_idx]
  # Guess for ascending inflection: halfway to the peak age
  initial_inflection_asc <- if (max_idx > 1) ages[floor(max_idx / 2)] else ages[1]
  # Guess for descending inflection: halfway between the peak and the max age
  initial_inflection_desc <- if (max_idx < length(ages)) ages[floor((max_idx + length(ages)) / 2)] else ages[length(ages)]

  # Perform the optimization using L-BFGS-B
  optimization_result <- stats::optim(
    # Initial parameter guesses: [inflection_asc, slope_asc, inflection_desc, slope_desc, asymptote, shape]
    par = c(initial_inflection_asc, 0.5, initial_inflection_desc, 0.5, max_val, 2.0),
    fn = objective_function_gamma,
    method = "L-BFGS-B",
    # Lower and upper bounds for the parameters
    lower = c(min(ages), 0.01, min(ages), 0.01, 1e-3, 0.1),
    upper = c(max(ages) + 1, 10, max(ages) + 1, 10, max_val * 2, 100)
  )

  # We drop parameter 5 (asymptote) and 6 (shape), returning only the 4 structural parameters for FIMS.
  tibble::tibble(
    model_family = "catch_at_age",
    module_name = NA_character_,
    fleet_name = NA_character_,
    module_type = "DoubleLogistic",
    label = c("inflection_point_asc", "slope_asc", "inflection_point_desc", "slope_desc"),
    age = NA_real_,
    length = NA_real_,
    value = c(
      optimization_result[["par"]][1],
      optimization_result[["par"]][2],
      optimization_result[["par"]][3],
      optimization_result[["par"]][4]
    ),
    estimation_type = "fixed_effects",
    distribution_type = NA_character_,
    distribution = NA_character_
  )
}
