#' Estimate true maturity parameters from ecosystem model input
#'
#' @param spawning_proportion A numeric vector of spawning proportions (0 to 1)
#'   for each functional group within a species. The values can be obtained from
#'   Ecopath -> Input -> Basic input -> Edit Multi_Stanza Groups.
#' @param ages A vector of ages.
#' @param functional_form A character string specifying the curve
#'   type. Currently supports "logistic".
#'
#' @return A named list containing the estimated 'inflection_point' and 'slope'.
#' @export
estimate_true_maturity <- function(ages, spawning_proportion, functional_form = "logistic") {
  # Validate functional form choice
  functional_form <- match.arg(functional_form)

  # Input validation
  if (length(ages) != length(spawning_proportion)) {
    cli::cli_abort("The 'ages' and 'spawning_proportion' vectors must be of equal length.")
  }
  if (any(spawning_proportion < 0 | spawning_proportion > 1)) {
    cli::cli_abort("Spawning proportions must be between 0 and 1.")
  }

  # TODO: check if we should use a different objective function and
  # move it to estimate_logistic_parameters()
  # Objective function: Residual Sum of Squares (RSS) for bounded proportions
  objective_function_squares <- function(parameters) {
    inflection_point <- parameters[1]
    slope <- parameters[2]

    # For maturity, the upper asymptote is fixed at a biological max of 1.0
    predicted <- 1.0 / (1.0 + exp(-slope * (ages - inflection_point)))

    # Return total squared error to minimize (always finite)
    sum((spawning_proportion - predicted)^2)
  }

  # Provide initial parameter estimates
  half_max_idx <- which.min(abs(spawning_proportion - 0.5))
  initial_inflection <- if (length(half_max_idx) > 0) ages[half_max_idx] else stats::median(ages)

  # Perform the optimization securely
  optimization_result <- stats::optim(
    par = c(initial_inflection, 1.0), # Initial guess for inflection and slope
    fn = objective_function_squares,
    method = "L-BFGS-B",
    lower = c(min(ages), 0.01),
    upper = c(max(ages) + 1, 15)
  )

  tibble::tibble(
    model_family = "catch_at_age",
    module_name = "Maturity",
    fleet_name = NA_character_,
    module_type = "Logistic",
    label = c("inflection_point", "slope"),
    age = NA_real_,
    length = NA_real_,
    time = NA_integer_,
    value = c(optimization_result[["par"]][1], optimization_result[["par"]][2]),
    estimation_type = "constant",
    distribution_type = NA_character_,
    distribution = NA_character_
  )
}

# #' Estimate true maturity parameters from dynamic ecosystem model weight outputs
# #'
# #' @description
# #' This function takes dynamic weight-at-age/stanza data from an ecosystem model,
# #' transforms it into relative length-at-age, and fits a logistic maturity ogive
# #' using a Gamma likelihood framework to estimate both the inflection point and slope.
# #'
# #' @param data A tibble containing filtered ecosystem model weight output for a single
# #'   species, typically generated by calling [load_model()] followed by
# #'   [get_truth()]. Must contain the columns:
# #'   "species_name", "truth_label", "truth_type", "truth_time_step",
# #'   "truth_group", "truth_year", "truth_unit", and "truth_value". The data should
# #'   be pre-filtered to a single species; if multiple species are detected in
# #'   the data, an error is issued.
# #' @param ages A **named numeric vector** where the names correspond exactly to the
# #'   unique stanza labels in the `truth_group` column from `data`, and the values
# #'   represent the representative structural ages or stanza midpoints.
# #' @param w_mat_ratio The Wmaturity/Winf ratio from Ecopath (e.g., 0.237).
# #'
# #' @return A tibble in NOAA-FIMS format containing estimated parameter values.
# #' @export
# estimate_true_maturity <- function(data,
#                                    ages = NULL,
#                                    w_mat_ratio,
#                                    functional_form = c("logistic")) {
#   # Validate inputs
#   ages <- validate_data_and_ages(data, ages)

#   # Ensure tracking order is strictly based on ascending age scale sorting
#   sorted_age_mapping <- sort(ages)
#   ordered_groups <- names(sorted_age_mapping)
#   numeric_ages_vector <- unname(sorted_age_mapping)

#   # Check structure metrics on the resolved numeric age vector
#   if (is.unsorted(numeric_ages_vector, strictly = TRUE)) {
#     cli::cli_abort("Resolved numeric age scales must layout in a strictly increasing sequence.")
#   }

#   # Determine unique time combinations based on truth_year
#   time_combinations <- data |>
#     dplyr::select(truth_year) |>
#     dplyr::distinct()

#   helper_function_name <- paste0("estimate_", functional_form, "_parameters")

#   # Calculate baseline biological target length (L50) using relative cube-root scaling
#   w_mat_relative <- 1.0 * w_mat_ratio
#   L50_target <- (w_mat_relative)^(1 / 3)

#   # Map Dynamic Weights to Logistic Maturity Parameters by Year
#   results_yearly <- data |>
#     dplyr::group_by(truth_year) |>
#     dplyr::reframe(
#       {
#         current_groups <- as.character(truth_group)
#         current_age_mapping <- sort(sorted_age_mapping[current_groups])
#         current_ordered_groups <- names(current_age_mapping)
#         current_numeric_ages <- unname(current_age_mapping)

#         # Pull dynamic Ecosim weights matching the sorted group sequence
#         weight_vector <- truth_value[match(current_ordered_groups, current_groups)]

#         # Scale weights relatively to match our w_inf = 1.0 anchor
#         max_weight <- max(weight_vector, na.rm = TRUE)
#         weight_vector_relative <- weight_vector / max_weight

#         # Convert relative weights to relative lengths via the multi-stanza cube-root rule
#         length_vector <- (weight_vector_relative)^(1 / 3)

#         # Build an observed empirical maturity vector based on EwE's threshold rules
#         # (1 if length >= target L50, 0 otherwise) to guide our curve fitter
#         empirical_maturity <- ifelse(length_vector >= L50_target, 1.0, 0.0)

#         # Run the helper function
#         params <- do.call(
#           helper_function_name,
#           list(raw_values = empirical_maturity, ages = current_numeric_ages)
#         )
#         # Return the parameters data frame directly inside summarize()
#         params
#       },
#       .groups = "drop"
#     ) |>
#     dplyr::rename(
#       time = truth_year
#     ) |>
#     dplyr::mutate(
#       module_name = "Maturity"
#     ) |>
#     dplyr::select(
#       model_family, module_name, fleet_name, module_type, label,
#       age, length, time, value,
#       estimation_type, distribution_type, distribution
#     )

#   # Check if parameter values vary significantly across years
#   is_time_varying <- results_yearly |>
#     dplyr::group_by(label) |>
#     dplyr::summarise(
#       variance = if (dplyr::n() > 1) stats::var(value, na.rm = TRUE) else 0,
#       .groups = "drop"
#     ) |>
#     dplyr::summarise(varying = any(variance > 1e-7, na.rm = TRUE)) |>
#     dplyr::pull(varying)

#   # Collapse or keep time-series records based on variance evaluation
#   if (is_time_varying) {
#     results <- results_yearly
#   } else {
#     results <- results_yearly |>
#       dplyr::distinct(
#         model_family, module_name, fleet_name, module_type, label,
#         age, length, .keep_all = TRUE
#       ) |>
#       dplyr::mutate(time = NA_integer_)
#   }
# }
