# Update /data when files in /data-raw are changed
# This workflow runs R code to regenerate data in /data when files in /data-raw are changed.
# Once the update is complete, the changes are committed.
# If 'commit-directly' is set to false (the default), a pull request will be opened 
# to the branch where the workflow was triggered. The PR will contain the commit with updated data.
# If 'commit-directly' is set to true, changes are pushed directly to the triggering branch.
# Note that the job will fail if force pushing is required.
on:
 workflow_call:
   secrets:
     PAT:
       required: false
   inputs:
     commit-directly:
       required: false
       type: boolean
       default: false

# Give the fewest permissions possible. content and pull-requests are necessary.
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: write
  pull-requests: write

# Cancel runs happening simultaneously on the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: update data

jobs:
  update-data-r:
    name: update R data from /data-raw
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - name: setup env using GITHUB_TOKEN, if no pat
        if: env.GITHUB_PAT == ''
        run: echo "GITHUB_PAT=${{ secrets.GITHUB_TOKEN}}" >> "$GITHUB_ENV"

      - name: checkout, make changes and submit as pr on new branch
        if: inputs.commit-directly == false
        uses: actions/checkout@v4
        
      - name: checkout, make changes directly
        if: inputs.commit-directly == true
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            devtools

      - name: Run R code to update files in /data
        run: |
          devtools::install()
          r_scripts <- list.files("data-raw", pattern = "\\.R$", full.names = TRUE)
          if (length(r_scripts) > 0) {
            for (script in r_scripts) {
              # Capture exit code so failures actually stop the GHA runner
              status <- system(paste("Rscript ", shQuote(script)))
              if (status != 0) stop(paste("Script failed:", script))
            }
          } else {
            message("No R scripts found in /data-raw.")
          }
        shell: Rscript {0}
        
      - name: commit if using commit directly
        if: inputs.commit-directly == true
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'update data from /data-raw'
      
      - name: specify base branch
        id: specify-base
        if: ${{ inputs.commit-directly == false }}
        run: |
          if [ -n "${{ github.head_ref }}" ]; then
            echo "base=${{github.head_ref}}" >> "$GITHUB_OUTPUT"
          elif [ -n "${{ github.ref_name }}" ]; then
            echo "base=${{github.ref_name}}" >> "$GITHUB_OUTPUT"
          else
            echo "both github.head_ref and github.ref_name do not exist" >&2
            exit 1
          fi  
      
      - name: Create Pull Request
        if: ${{inputs.commit-directly == false}}
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'update R data from /data-raw'
          token: ${{ env.GITHUB_PAT }}
          branch: update-data-${{ github.ref_name }}
          base: ${{ steps.specify-base.outputs.base }}
          title: 'update R data'
          body: |
           Auto-generated by [update-data-r.yml][1]

             [1]: https://github.com/NOAA-FIMS/ecosystemom/tree/main/.github/workflows/update-data-r.yml
